In [1]:
import numpy as np

In [2]:
array = np.array([9,8,7,6,5])
print (array)

[9 8 7 6 5]


In [3]:
print(array[2])

7


In [5]:
array2d = np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(array2d)

[[1 2 3 4 5]
 [5 4 3 2 1]]


In [6]:
# Accessing the 3rd element of the first array
print(array2d[0,2])

3


In [7]:
array3d = np.array([[2,4,6,8],[1,3,5,7],[10,20,30,40]])
print(array3d)

[[ 2  4  6  8]
 [ 1  3  5  7]
 [10 20 30 40]]


In [8]:
print(array3d[1,2])

5


In [9]:
array5d = np.array([[2,4,6,8],[1,3,5,7],[20,40,60,80],[10,30,50,70],[100,90,80,70]])
print(array5d)


[[  2   4   6   8]
 [  1   3   5   7]
 [ 20  40  60  80]
 [ 10  30  50  70]
 [100  90  80  70]]


In [13]:
print(f"This is the number ten:{array5d[3,0]}, followed by twenty: {array5d[2,0]} followed by thirty: {array5d[3,1]}")

This is the number ten:10, followed by twenty: 20 followed by thirty: 30


In [14]:
print("This is the number ten:",array5d[3,0], "followed by twenty:", array5d[2,0])

This is the number ten: 10 followed by twenty: 20
